# Pin npm packages by running ./bin/importmap

pin "application"
pin "sw_register", to: "sw_register.js"
pin "lib/length_convert", to: "lib/length_convert.js"
pin "lib/tag_rule", to: "lib/tag_rule.js"
pin "lib/leaflet_default_icons", to: "lib/leaflet_default_icons.js"
pin "lib/leaflet_teardown", to: "lib/leaflet_teardown.js"
pin "lib/ios_device", to: "lib/ios_device.js"
pin "offline/sync", to: "offline/sync.js"
pin "offline/session", to: "offline/session.js"
pin "offline/current_user", to: "offline/current_user.js"
pin "offline/db", to: "offline/db.js"
pin "offline/blob", to: "offline/blob.js"
pin "offline/limits", to: "offline/limits.js"
pin "offline/form_data", to: "offline/form_data.js"
pin "offline/api_error", to: "offline/api_error.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "idb" # @8.0.3
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "leaflet" # @1.9.4
pin "trix"
pin "@rails/actiontext", to: "actiontext.esm.js"
